### ISSUE TITLE
Zlib support

### ISSUE THREAD

**Issue by lockie** [cl-docker-images/sbcl#1]
Hello!
Thanks for the awesome docker image!
I have a little suggestion. Looks like the SBCL inside the image is built without zlib support (judging by the size of the core produced by `save-lisp-and-die`). Could you please consider building SBCL with zlib support on?
Thanks in advance!

**Comment by lockie** [comment]
After research I've found out this just requires adding `--fancy` argument to `make.sh` script invocation - `:sb-core-compression` considered to be a fancy feature :sweat_smile:

**Comment by daewok** [comment]
Even though I almost always use core compression, it was a conscious decision to not include it. I want the base image to build using upstream's defaults. One reason for that is I don't want to arbitrate what should be default. For example, `--fancy` also includes `:sb-xref-for-internals`, which increases the core size.

However, it might make sense to make a new set of tags that are built with `--fancy` since that's probably what a lot of people do actually want. I'll look into doing that for SBCL 2.0.4. I hope to get that version out this week (I'm just running into some issues with the Alpine images I haven't been able to fix yet). In the meantime you can use the Build images https://github.com/daewok/docker-sbcl#-build-images to easily build one with `:sb-core-compression` present.

**Comment by lockie** [comment]
> I'll look into doing that for SBCL 2.0.4.

Thank you very much! Looking forward to it.

> I'm just running into some issues with the Alpine images I haven't been able to fix yet

I have some experience with Alpine Linux (and enough perseverance to deal with its oddities :sweat_smile:), so I'll happily look into those if you want. Feel free to drop an email to awkravchuk at geemail.

**Comment by daewok** [comment]
2.0.4 images pushed, along with a new fancy variant.

**Comment by lockie** [comment]
Thanks a lot!
